# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import tensor_pb2 as tensor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cserver.proto\x1a\x0ctensor.proto\"/\n\x11\x43heckBufferStatus\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\"#\n\x11\x42ufferStatusReply\x12\x0e\n\x06status\x18\x01 \x01(\t\">\n\x0bReduceChunk\x12\x0f\n\x07ring_id\x18\x01 \x01(\x05\x12\x1e\n\ndata_chunk\x18\x02 \x01(\x0b\x32\n.DataChunk\">\n\x0bGatherChunk\x12\x0f\n\x07ring_id\x18\x01 \x01(\x05\x12\x1e\n\ndata_chunk\x18\x02 \x01(\x0b\x32\n.DataChunk\"<\n\tDataChunk\x12\x0e\n\x06\x62uffer\x18\x01 \x01(\x0c\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x11\n\tdata_size\x18\x03 \x01(\x05\"\x1e\n\rReceivedChunk\x12\r\n\x05reply\x18\x01 \x01(\x08\x32\xdd\x01\n\nCommServer\x12\x30\n\x0bsend_buffer\x12\x0b.SendTensor\x1a\x10.SendTensorReply\"\x00(\x01\x12\x39\n\rbuffer_status\x12\x12.CheckBufferStatus\x1a\x12.BufferStatusReply\"\x00\x12\x30\n\x0creduce_chunk\x12\x0c.ReduceChunk\x1a\x0e.ReceivedChunk\"\x00(\x01\x12\x30\n\x0cgather_chunk\x12\x0c.GatherChunk\x1a\x0e.ReceivedChunk\"\x00(\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CHECKBUFFERSTATUS._serialized_start=30
  _CHECKBUFFERSTATUS._serialized_end=77
  _BUFFERSTATUSREPLY._serialized_start=79
  _BUFFERSTATUSREPLY._serialized_end=114
  _REDUCECHUNK._serialized_start=116
  _REDUCECHUNK._serialized_end=178
  _GATHERCHUNK._serialized_start=180
  _GATHERCHUNK._serialized_end=242
  _DATACHUNK._serialized_start=244
  _DATACHUNK._serialized_end=304
  _RECEIVEDCHUNK._serialized_start=306
  _RECEIVEDCHUNK._serialized_end=336
  _COMMSERVER._serialized_start=339
  _COMMSERVER._serialized_end=560
# @@protoc_insertion_point(module_scope)
