# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensor.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ctensor.proto\">\n\nSendTensor\x12\"\n\x0ctensor_chunk\x18\x01 \x01(\x0b\x32\x0c.TensorChunk\x12\x0c\n\x04type\x18\x02 \x01(\t\" \n\x0fSendTensorReply\x12\r\n\x05reply\x18\x01 \x01(\x08\"@\n\x0bTensorChunk\x12\x0e\n\x06\x62uffer\x18\x01 \x01(\x0c\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x13\n\x0btensor_size\x18\x03 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tensor_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SENDTENSOR._serialized_start=16
  _SENDTENSOR._serialized_end=78
  _SENDTENSORREPLY._serialized_start=80
  _SENDTENSORREPLY._serialized_end=112
  _TENSORCHUNK._serialized_start=114
  _TENSORCHUNK._serialized_end=178
# @@protoc_insertion_point(module_scope)
