apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ravnest-sql-agent.fullname" . }}-db
  labels:
    {{- include "ravnest-sql-agent.labels" . | nindent 4 }}
    component: database
spec:
  accessModes:
    - {{ .Values.database.accessMode | default "ReadWriteOnce" }}
  {{- if .Values.database.storageClass }}
  storageClassName: {{ .Values.database.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.database.storageSize }}
