apiVersion: v1
kind: Service
metadata:
  name: {{ include "ravnest-sql-agent.fullname" . }}-sql
  labels:
    {{- include "ravnest-sql-agent.labels" . | nindent 4 }}
    component: sql
spec:
  type: ClusterIP
  selector:
    {{- include "ravnest-sql-agent.selectorLabels" . | nindent 4 }}
    component: sql
  ports:
    - name: http
      port: {{ .Values.sql.port }}
      targetPort: http
      protocol: TCP
